/** Lista centralizada de equipamentos — usada no select com busca da etapa Equipe e Equipamentos do RDO. */
export const RDO_EQUIPMENT_NAMES: string[] = [
  "Escavadeira hidráulica",
  "Retroescavadeira",
  "Pá carregadeira",
  "Motoniveladora",
  "Trator de esteira",
  "Trator agrícola",
  "Rolo compactador",
  "Rolo pé de carneiro",
  "Rolo liso vibratório",
  "Caminhão basculante",
  "Caminhão betoneira",
  "Caminhão pipa",
  "Caminhão munck",
  "Caminhão comboio",
  "Guindaste",
  "Mini carregadeira",
  "Empilhadeira",
  "Plataforma elevatória",
  "Bomba de concreto",
  "Betoneira",
  "Compactador de solo",
  "Placa vibratória",
  "Martelete rompedor",
  "Gerador de energia",
  "Compressor de ar",
  "Máquina de solda",
  "Serra policorte",
  "Serra circular",
  "Vibrador de concreto",
  "Régua vibratória",
  "Andaime",
  "Escora metálica",
  "Forma metálica",
  "Niveladora",
  "Perfuratriz",
  "Rompedor hidráulico",
  "Munck",
  "Veículo utilitário",
  "Drone de inspeção",
  "Estação total",
  "Nível a laser",
  "GPS geodésico",
  "Outro",
];

export const RDO_EQUIPMENT_NAME_OPTIONS = RDO_EQUIPMENT_NAMES.map((value) => ({ value, label: value }));
