/** Lista centralizada de funções de obra — usada nos selects de Equipe da Obra e nas etapas de RDO. */
export const WORK_FUNCTIONS: string[] = [
  "Engenheiro Residente",
  "Engenheiro Civil",
  "Engenheiro de Campo",
  "Engenheiro de Planejamento",
  "Engenheiro de Produção",
  "Engenheiro de Segurança",
  "Coordenador de Obras",
  "Gestor de Contrato",
  "Fiscal de Obra",
  "Fiscal SUAPE",
  "Fiscal Externo",
  "Supervisor de Obras",
  "Técnico de Edificações",
  "Técnico de Segurança",
  "Técnico de Qualidade",
  "Técnico Ambiental",
  "Apontador",
  "Mestre de Obras",
  "Encarregado Geral",
  "Encarregado de Terraplenagem",
  "Encarregado de Fundação",
  "Encarregado de Concretagem",
  "Encarregado de Estrutura",
  "Encarregado de Alvenaria",
  "Líder de Equipe",
  "Pedreiro",
  "Servente",
  "Carpinteiro",
  "Armador",
  "Ferreiro",
  "Soldador",
  "Pintor",
  "Eletricista",
  "Encanador",
  "Bombeiro Hidráulico",
  "Montador",
  "Serralheiro",
  "Caldeireiro",
  "Operador de Máquinas",
  "Motorista",
  "Ajudante Geral",
  "Auxiliar de Obras",
  "Topógrafo",
  "Auxiliar de Topografia",
  "Operador de Escavadeira",
  "Operador de Retroescavadeira",
  "Operador de Guindaste",
  "Operador de Munck",
  "Operador de Rolo Compactador",
  "Operador de Pá Carregadeira",
  "Operador de Motoniveladora",
  "Operador de Trator",
  "Operador de Empilhadeira",
  "Operador de Bomba de Concreto",
  "Motorista de Caminhão Basculante",
  "Motorista de Caminhão Betoneira",
  "Motorista de Caminhão Pipa",
  "Inspetor de Qualidade",
  "Laboratorista de Concreto",
  "Técnico de Controle Tecnológico",
  "Responsável por Medição",
  "Responsável por Documentação Técnica",
  "Responsável por Evidências Fotográficas",
  "Bombeiro Civil",
  "Brigadista",
  "Sinaleiro",
  "Vigia",
  "Equipe de Terraplenagem",
  "Equipe de Fundação",
  "Equipe de Concretagem",
  "Equipe de Armação",
  "Equipe de Forma",
  "Equipe de Alvenaria",
  "Equipe de Instalações Elétricas",
  "Equipe de Instalações Hidráulicas",
  "Equipe de Pavimentação",
  "Equipe de Drenagem",
  "Equipe de Montagem",
  "Equipe de Acabamento",
  "Equipe de Manutenção",
  "Outro",
];

export const WORK_FUNCTION_OPTIONS = WORK_FUNCTIONS.map((value) => ({ value, label: value }));
